-- 코드를 입력하세요
SELECT DATE_FORMAT(O.SALES_DATE,'%Y') AS YEAR, CAST(DATE_FORMAT(O.SALES_DATE,'%m') AS UNSIGNED) AS MONTH,
    (case
        WHEN GENDER IS NULL THEN 2
        WHEN GENDER = 1 THEN 1
        WHEN GENDER = 0 THEN 0
    end) AS GENDER,
    COUNT(distinct(U.USER_ID))AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
;