-- 코드를 입력하세요
SELECT H.HISTORY_ID, 
    CAST(
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE * 
        (1 - IFNULL(CAST(REPLACE(P.DISCOUNT_RATE, '%', '') AS UNSIGNED), 0) / 100) 
        AS SIGNED
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
left outer JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
AND (
       (P.DURATION_TYPE = '7일 이상'  AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30)
    OR (P.DURATION_TYPE = '30일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90)
    OR (P.DURATION_TYPE = '90일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90)
     )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC

;


# SELECT H.HISTORY_ID, H.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, P.DURATION_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
# JOIN CAR_RENTAL_COMPANY_CAR AS C
# ON H.CAR_ID = C.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
# ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE = '트럭'
# ;