-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN ='N' AND A.APNT_YMD >= '2022-04-13 00:00:00' and A.APNT_YMD < '2022-04-14 00:00:00'
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD ASC
;