-- 코드를 입력하세요
# WITH RECURSIVE hours AS (
#     SELECT 0 AS HOUR
#     UNION ALL
#     SELECT HOUR + 1
#     FROM hours
#     WHERE HOUR < 23
# )

WITH hours AS(
    SELECT 0 AS HOUR
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
    UNION ALL SELECT 5
    UNION ALL SELECT 6
    UNION ALL SELECT 7
    UNION ALL SELECT 8
    UNION ALL SELECT 9
    UNION ALL SELECT 10
    UNION ALL SELECT 11
    UNION ALL SELECT 12
    UNION ALL SELECT 13
    UNION ALL SELECT 14
    UNION ALL SELECT 15
    UNION ALL SELECT 16
    UNION ALL SELECT 17
    UNION ALL SELECT 18
    UNION ALL SELECT 19
    UNION ALL SELECT 20
    UNION ALL SELECT 21
    UNION ALL SELECT 22
    UNION ALL SELECT 23
    
)

SELECT 
    h.HOUR,
    COALESCE(COUNT(A.DATETIME), 0) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS A
  ON HOUR(A.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR;

# SELECT CAST(DATE_FORMAT(DATETIME,'%H') AS UNSIGNED) AS HOUR,
#     COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# ORDER BY HOUR ASC;



# SELECT CAST(DATE_FORMAT(DATETIME,'%h') AS UNSIGNED) FROM ANIMAL_OUTS;
# SELECT * FROM ANIMAL_OUTS;