-- 코드를 입력하세요
# SELECT DATE_FORMAT(H.start_date,'%m') AS MONTH
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# GROUP BY DATE_FORMAT(H.start_date,'%m')
# having H.START_DATE BETWEEN '2022-08-01' and '2022-09-30' and SUM(H.CAR_ID) >= 5

# ;


SELECT CAST(DATE_FORMAT(H.start_date,'%m') as UNSIGNED) AS MONTH, H.CAR_ID AS CAR_ID, COUNT(H.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
where H.START_DATE BETWEEN '2022-08-01' and '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING H.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
ORDER BY MONTH ASC, CAR_ID DESC;
