SELECT
    CASE
        WHEN SUM(S.NAME = 'Python') > 0 
             AND SUM(S.CATEGORY = 'Front End') > 0 THEN 'A'
        WHEN SUM(S.NAME = 'C#') > 0 THEN 'B'
        WHEN SUM(S.CATEGORY = 'Front End') > 0 THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S
  ON (D.SKILL_CODE & S.CODE) = S.CODE
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC;
